### ISSUE TITLE
Update needed in line with Markdown 3.4.x

### ISSUE THREAD

**Issue by stevejalim** [aleray/mdx_outline#6]
The shift to Markdown 3.4 removed some previously deprecated objects - [relevant release notes here](https://github.com/Python-Markdown/markdown/blob/master/docs/change_log/release-3.4.md](release notes here))

Without the upgrade, `mdx_outline` can fail - eg in `github.com/mozilla/bedrock/` I just hit:

```
  File "/app/bedrock/legal_docs/models.py", line 12, in <module>
    from mdx_outline import OutlineExtension
  File "/venv/lib/python3.9/site-packages/mdx_outline.py", line 143, in <module>
    from markdown.util import etree
ImportError: cannot import name 'etree' from 'markdown.util' (/venv/lib/python3.9/site-packages/markdown/util.py)
```

I'll try to update this on our fork of the project, and will offer back a PR, but logging the issue here for visibility for others

**Comment by stevejalim** [comment]
Current PR against my team's fork: https://github.com/mozmeao/mdx_outline/pull/1

**Comment by stevejalim** [comment]
Update: our fork's default branch has 3.4 support, but no current guarantee of backwards compatibility https://github.com/mozmeao/mdx_outline

**Comment by aleray** [comment]
Thanks for your work!
